version: "3.9"

services:
    stripe-cli:
        image: stripe/stripe-cli
        container_name: stripe-cli
        command:
            - listen
            - "--api-key"
            - ${STRIPE_API_KEY}
            - "--device-name"
            - "Qwerky"
            - "--forward-to"
            - "http://localhost:3000/api/stripe/webhook"
            - "--skip-verify"
        network_mode: host
        env_file:
            - ./.env.development

    postgres-server:
        image: postgres:14.1-alpine
        container_name: Database
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres-server:/var/lib/postgresql/data
        env_file:
            - ./.env.development

volumes:
    postgres-server:
        driver: local
