import { ArtistStyleMeta } from "@/types/sharedTypes";

export const artStyleNames = [
    '',
    'Abstract art',
    'Abstractionism',
    'Academic art',
    'Aestheticism',
    'Art Brut',
    'Art Deco',
    'Art Nouveau',
    'Baroque',
    'Bauhaus',
    'Body art',
    'Byzantine art',
    'Caravaggism',
    'Classicism',
    'Color field painting',
    'Conceptual art',
    'Constructivism',
    'Cubism',
    'Dadaism',
    'Digital art',
    'Expressionism',
    'Fauvism',
    'Figurative art',
    'Fluxus',
    'Futurism',
    'Graffiti art',
    'Harlem Renaissance',
    'High Renaissance',
    'Hyperrealism',
    'Impressionism',
    'Installation art',
    'Kinetic art',
    'Land art',
    'Lowbrow art',
    'Magic realism',
    'Mannerism',
    'Medieval art',
    'Minimalism',
    'Modernism',
    'Naive art',
    'Naturalism',
    'Neo-classicism',
    'Neo-expressionism',
    'Neo-pop',
    'Op art',
    'Orientalism',
    'Outsider art',
    'Performance art',
    'Pointillism',
    'Pop art',
    'Post-Impressionism',
    'Postmodernism',
    'Precisionism',
    'Pre-Raphaelitism',
    'Realism',
    'Regionalism',
    'Rococo',
    'Romanticism',
    'Social Realism',
    'Street art',
    'Surrealism',
    'Symbolism',
    'Synthetic Cubism',
    'Tachisme',
    'The Ashcan School',
    'The Baroque',
    'The Hudson River School',
    'The Northern Renaissance',
    'The Renaissance',
    'The Rococo',
    'The School of London',
    'The Vienna Secession',
    'Tonalism',
    'Ukiyo-e',
    'Video art',
    'Victorian art',
    'Abstract expressionism',
    'Afrofuturism',
    'Algorithmic art',
    'Arte Povera',
    'Assemblage',
    'Black art',
    'Chinoiserie',
    'Cinema Verite',
    'Concrete art',
    'Contemporary art',
    'Cyberpunk',
    'Drip painting',
    'Encaustic',
    'Environmental art',
    'Figuration Libre',
    'Fluxus',
    'Geometric abstraction',
    'Graffito',
    'Happening',
    'Hard-edge painting',
    'Indian art',
    'Institutional critique',
    'Intuitive art',
    'Kinetic art',
    'Light and Space'
];

export const artistStyleMap: ArtistStyleMeta[] = [
    {
        style: 'Pop Structural',
        artistName: 'Yayoi Kusama',
        imageUrl: '/artists/yayoi_kusama.png',
        wiki: 'https://en.wikipedia.org/wiki/Yayoi_Kusama'
    },
    {
        artistName: 'Andy Warhol',
        style: 'Pop Art',
        imageUrl: '/artists/andy_worhol.png',
        wiki: 'https://en.wikipedia.org/wiki/Andy_Warhol'
    },
    {
        style: 'Abstract Expressionism',
        artistName: 'Jackson Pollock',
        imageUrl: '/artists/jackson_pollock.png',
        wiki: 'https://en.wikipedia.org/wiki/Jackson_Pollock'
    },
    {
        style: 'Abstract Illusionism',
        artistName: 'Richard Estes',
        imageUrl: '/artists/richard_estes.png',
        wiki: 'https://en.wikipedia.org/wiki/Richard_Estes'
    },
    // { style: 'Art Nouveau', artistName: 'Alphonse Mucha', imageUrl: '/artists/Alphonse_Mucha.png', wiki: '' },
    // { style: 'Classicism', artistName: 'Nicolas Poussin', imageUrl: '/artists/Nicolas_Poussin.png', wiki: '' },
    // { style: 'Conceptual Art', artistName: 'Marcel Duchamp', imageUrl: '/artists/Marcel_Duchamp.png', wiki: '' },
    // { style: 'Constructivism', artistName: 'Alexander Rodchenko', imageUrl: '/artists/Alexander_Rodchenko.png', wiki: '' },
    // { style: 'Cubism', artistName: 'Pablo Picasso', imageUrl: '/artists/Pablo_Picasso.png', wiki: '' },
    // { style: 'Dadaism', artistName: 'Marcel Duchamp', imageUrl: '/artists/Marcel_Duchamp.png', wiki: '' },
    // { style: 'Expressionism', artistName: 'Edvard Munch', imageUrl: '/artists/Edvard_Munch.png', wiki: '' },
    // { style: 'Fauvism', artistName: 'Henri Matisse', imageUrl: '/artists/Henri_Matisse.png', wiki: '' },
    // { style: 'Feminist Art', artistName: 'Judy Chicago', imageUrl: '/artists/Judy_Chicago.png', wiki: '' },
    // { style: 'Figurative Art', artistName: 'Lucian Freud', imageUrl: '/artists/Lucian_Freud.png', wiki: '' },
    // { style: 'Hyperrealism', artistName: 'Chuck Close', imageUrl: '/artists/Chuck_Close.png', wiki: '' },
    // { style: 'Impressionism', artistName: 'Claude Monet', imageUrl: '/artists/Claude_Monet.png', wiki: '' },
    // { style: 'Fluxus', artistName: 'Yoko Ono', imageUrl: '/artists/Yoko_Ono.png', wiki: '' },
    // { style: 'Futurism', artistName: 'Umberto Boccioni', imageUrl: '/artists/Umberto_Boccioni.png', wiki: '' },
    // { style: 'Bauhaus', artistName: 'Wassily Kandinsky', imageUrl: '/artists/Wassily_Kandinsky.png', wiki: '' },
    // { style: 'Kinetic Art', artistName: 'Jean Tinguely', imageUrl: '/artists/Jean_Tinguely.png', wiki: '' },
    // { style: 'Land Art', artistName: 'Robert Smithson', imageUrl: '/artists/Robert_Smithson.png', wiki: '' },
    // { style: 'Lyrical Abstraction', artistName: 'Ronnie Landfield', imageUrl: '/artists/Ronnie_Landfield.png', wiki: '' },
    // { style: 'Magic Realism', artistName: 'Frida Kahlo', imageUrl: '/artists/Frida_Kahlo.png', wiki: '' },
    // { style: 'Manierism', artistName: 'El Greco', imageUrl: '/artists/El_Greco.png', wiki: '' },
    // { style: 'Minimal Art', artistName: 'Donald Judd', imageUrl: '/artists/Donald_Judd.png', wiki: '' },
    // { style: 'Naive Art', artistName: 'Henri Rousseau', imageUrl: '/artists/Henri_Rousseau.png', wiki: '' },
    // { style: 'Neo-Geo', artistName: 'Peter Halley', imageUrl: '/artists/Peter_Halley.png', wiki: '' },
    // { style: 'Neo-Impressionism', artistName: 'Georges Seurat', imageUrl: '/artists/Georges_Seurat.png', wiki: '' },
    // { style: 'Neo-Plasticism', artistName: 'Piet Mondrian', imageUrl: '/artists/Piet_Mondrian.png', wiki: '' },
    // { style: 'Neo-Pop Art', artistName: 'Jeff Koons', imageUrl: '/artists/Jeff_Koons.png', wiki: '' },
    // { style: 'New Objectivity', artistName: 'Otto Dix', imageUrl: '/artists/Otto_Dix.png', wiki: '' },
    // { style: 'Op Art', artistName: 'Bridget Riley', imageUrl: '/artists/Bridget_Riley.png', wiki: '' },
    // { style: 'Photorealism', artistName: 'Richard Estes', imageUrl: '/artists/Richard_Estes.png', wiki: '' },
    // { style: 'Pointillism', artistName: 'Georges Seurat', imageUrl: '/artists/Georges_Seurat.png', wiki: '' },
    // { style: 'Pop Art', artistName: 'Andy Warhol', imageUrl: '/artists/Andy_Warhol.png', wiki: '' },
    // { style: 'Post-Minimalism', artistName: 'Eva Hesse', imageUrl: '/artists/Eva_Hesse.png', wiki: '' },
    // { style: 'Precisionism', artistName: 'Charles Sheeler', imageUrl: '/artists/Charles_Sheeler.png', wiki: '' },
    // { style: 'Realism', artistName: 'Gustave Courbet', imageUrl: '/artists/Gustave_Courbet.png', wiki: '' },
    // { style: 'Romanesque Art', artistName: 'Gero Cross', imageUrl: '/artists/Gero_Cross.png', wiki: '' },
    // { style: 'Russian Constructivism', artistName: 'El Lissitzky', imageUrl: '/artists/El_Lissitzky.png', wiki: '' },
    // { style: 'Sculpture', artistName: 'Auguste Rodin', imageUrl: '/artists/Auguste_Rodin.png', wiki: '' },
    // { style: 'Surrealism', artistName: 'Salvador Dali', imageUrl: '/artists/Salvador_Dali.png', wiki: '' },
    // { style: 'Symbolism', artistName: 'Gustav Klimt', imageUrl: '/artists/Gustav_Klimt.png', wiki: '' },
    // { style: 'Synthetic Cubism', artistName: 'Georges Braque', imageUrl: '/artists/Georges_Braque.png', wiki: '' },
    // { style: 'Suprematism', artistName: 'Kazimir Malevich', imageUrl: '/artists/Kazimir_Malevich.png', wiki: '' },
    // { style: 'YBAs (Young British Artists)', artistName: 'Damien Hirst', imageUrl: '/artists/Damien_Hirst.png', wiki: '' },
    // { style: 'Abstract Art', artistName: 'Kazimir Malevich', imageUrl: '/artists/Kazimir_Malevich.png', wiki: '' },
    // { style: 'Assemblage', artistName: 'Robert Rauschenberg', imageUrl: '/artists/Robert_Rauschenberg.png', wiki: '' },
    // { style: "Cigoli's Style", artistName: 'Lodovico Cigoli', imageUrl: '/artists/Lodovico_Cigoli.png', wiki: '' },
    // { style: 'Cloisonnism', artistName: 'Paul Gauguin', imageUrl: '/artists/Paul_Gauguin.png', wiki: '' },
    // { style: 'Contemporary Realism', artistName: 'Janet Fish', imageUrl: '/artists/Janet_Fish.png', wiki: '' },
    // { style: 'Constructive Art', artistName: 'Antoine Pevsner', imageUrl: '/artists/Antoine_Pevsner.png', wiki: '' },
    // { style: 'Dutch Realism', artistName: 'Frans Hals', imageUrl: '/artists/Frans_Hals.png', wiki: '' },
    // { style: 'Environmental Art', artistName: 'Maya Lin', imageUrl: '/artists/Maya_Lin.png', wiki: '' },
    // { style: 'Existential Art', artistName: 'Francis Bacon', imageUrl: '/artists/Francis_Bacon.png', wiki: '' },
    // { style: 'Fantastic Realism', artistName: 'Ernst Fuchs', imageUrl: '/artists/Ernst_Fuchs.png', wiki: '' },
    // { style: 'Figurative Expressionism', artistName: 'Francis Bacon', imageUrl: '/artists/Francis_Bacon.png', wiki: '' },
    // { style: 'Functional Art', artistName: 'Marcel Breuer', imageUrl: '/artists/Marcel_Breuer.png', wiki: '' },
    // { style: 'Geometric Abstraction', artistName: 'Sol LeWitt', imageUrl: '/artists/Sol_LeWitt.png', wiki: '' },
    // { style: 'Hard-edge Painting', artistName: 'Frank Stella', imageUrl: '/artists/Frank_Stella.png', wiki: '' },
    // { style: 'Historicism', artistName: 'William Butterfield', imageUrl: '/artists/William_Butterfield.png', wiki: '' },
    // { style: 'Hyperrealism', artistName: 'Chuck Close', imageUrl: '/artists/Chuck_Close.png', wiki: '' },
    // { style: 'Intervention Art', artistName: 'Jenny Holzer', imageUrl: '/artists/Jenny_Holzer.png', wiki: '' },
    // { style: 'Kinetic Art', artistName: 'Alexander Calder', imageUrl: '/artists/Alexander_Calder.png', wiki: '' },
    // { style: 'Land Art', artistName: 'Richard Long', imageUrl: '/artists/Richard_Long.png', wiki: '' },
    // { style: 'Les Nabis', artistName: 'Pierre Bonnard', imageUrl: '/artists/Pierre_Bonnard.png', wiki: '' },
    // { style: 'Light and Space', artistName: 'James Turrell', imageUrl: '/artists/James_Turrell.png', wiki: '' },
    // { style: 'Massurrealism', artistName: 'Rene Magritte', imageUrl: '/artists/Rene_Magritte.png', wiki: '' },
    // { style: 'Maximalism', artistName: 'Jeff Koons', imageUrl: '/artists/Jeff_Koons.png', wiki: '' },
    // { style: 'Minimalism', artistName: 'Donald Judd', imageUrl: '/artists/Donald_Judd.png', wiki: '' },
    // { style: 'Naive Art', artistName: 'Henri Rousseau', imageUrl: '/artists/Henri_Rousseau.png', wiki: '' },
    // { style: 'Neo-Dada', artistName: 'Jasper Johns', imageUrl: '/artists/Jasper_Johns.png', wiki: '' },
    // { style: 'Neo-Expressionism', artistName: 'Anselm Kiefer', imageUrl: '/artists/Anselm_Kiefer.png', wiki: '' },
    // { style: 'Neo-Impressionism', artistName: 'Georges Seurat', imageUrl: '/artists/Georges_Seurat.png', wiki: '' },
    // { style: 'Neo-Plasticism', artistName: 'Piet Mondrian', imageUrl: '/artists/Piet_Mondrian.png', wiki: '' },
    // { style: 'New Objectivity', artistName: 'Otto Dix', imageUrl: '/artists/Otto_Dix.png', wiki: '' },
    // { style: 'Op Art', artistName: 'Bridget Riley', imageUrl: '/artists/Bridget_Riley.png', wiki: '' },
    // { style: 'Organic Abstraction', artistName: 'Arshile Gorky', imageUrl: '/artists/Arshile_Gorky.png', wiki: '' },
    // { style: 'Orphism', artistName: 'Robert Delaunay', imageUrl: '/artists/Robert_Delaunay.png', wiki: '' },
    // { style: 'Outsider Art', artistName: 'Adolf Wölfli', imageUrl: '/artists/Adolf_Wölfli.png', wiki: '' },
    // { style: 'Performance Art', artistName: 'Marina Abramovic', imageUrl: '/artists/Marina_Abramovic.png', wiki: '' },
    // { style: 'Photo-Realism', artistName: 'Richard Estes', imageUrl: '/artists/Richard_Estes.png', wiki: '' },
    // { style: 'Pluralism', artistName: 'David Salle', imageUrl: '/artists/David_Salle.png', wiki: '' },
    // { style: 'Pointillism', artistName: 'Georges Seurat', imageUrl: '/artists/Georges_Seurat.png', wiki: '' },
    // { style: 'Pop Art', artistName: 'Andy Warhol', imageUrl: '/artists/Andy_Warhol.png', wiki: '' },
    // { style: 'Post-Minimalism', artistName: 'Eva Hesse', imageUrl: '/artists/Eva_Hesse.png', wiki: '' },
    // { style: 'Precisionism', artistName: 'Charles Sheeler', imageUrl: '/artists/Charles_Sheeler.png', wiki: '' },
    // { style: 'Realism', artistName: 'Gustave Courbet', imageUrl: '/artists/Gustave_Courbet.png', wiki: '' }

    // { style: 'Tenebrism', artistName: 'Caravaggio', imageUrl: '', wiki: '' },
    // { style: 'Ukiyo-e', artistName: 'Hokusai', imageUrl: '', wiki: '' },
    // { style: 'Egyptian Art', artistName: 'Nefertari', imageUrl: '', wiki: '' },
    // { style: 'Graffiti Art', artistName: 'Banksy', imageUrl: '', wiki: '' },
    // { style: 'Japanese Art', artistName: 'Hokusai', imageUrl: '', wiki: '' },
    // { style: 'Mannerism', artistName: 'Michelangelo', imageUrl: '', wiki: '' },
 
    // { style: 'Art Deco', artistName: 'Tamara de Lempicka', imageUrl: '', wiki: '' },
    // { style: 'Baroque', artistName: 'Peter Paul Rubens', imageUrl: '', wiki: '' },
    // { style: 'Gothic Art', artistName: 'Giotto di Bondone', imageUrl: '', wiki: '' },
    // { style: 'Post-Impressionism', artistName: 'Vincent van Gogh', imageUrl: '', wiki: '' },
    // { style: 'Pre-Raphaelitism', artistName: 'William Holman Hunt', imageUrl: '', wiki: '' },
    // { style: 'Proto-Renaissance', artistName: 'Giotto di Bondone', imageUrl: '', wiki: '' },
    // { style: 'Renaissance', artistName: 'Leonardo da Vinci', imageUrl: '', wiki: '' },
    // { style: 'Video Art', artistName: 'Nam June Paik', imageUrl: '', wiki: '' },
    // { style: 'Verism', artistName: 'Gian Lorenzo Bernini', imageUrl: '', wiki: '' },
    // { style: 'Gothic Art', artistName: 'Jan van Eyck', imageUrl: '', wiki: '' },
    // { style: 'Metaphysical Art', artistName: 'Giorgio de Chirico', imageUrl: '', wiki: '' },
    // { style: 'Mosaic', artistName: 'Giotto di Bondone', imageUrl: '', wiki: '' },
    // { style: 'Post-Impressionism', artistName: 'Vincent van Gogh', imageUrl: '', wiki: '' },
    // { style: 'Pre-Raphaelitism', artistName: 'William Holman Hunt', imageUrl: '', wiki: '' },
    // { style: 'Proto-Renaissance', artistName: 'Giotto di Bondone', imageUrl: '', wiki: '' },

    // { style: 'Caravaggism', artistName: 'Michelangelo Merisi da Caravaggio', imageUrl: '', wiki: '' },
    // { style: 'Installation Art', artistName: 'Christo and Jeanne-Claude', imageUrl: '', wiki: '' },
    // { style: 'Neo-Expressionism', artistName: 'Jean-Michel Basquiat', imageUrl: '', wiki: '' },
    // { style: 'Neoclassicism', artistName: 'Jacques-Louis David', imageUrl: '', wiki: '' },
    // { style: 'Rococo', artistName: 'Jean-Antoine Watteau', imageUrl: '', wiki: '' },
    // { style: 'Tachisme', artistName: 'Hans Hartung', imageUrl: '', wiki: '' },
    // { style: 'Installation Art', artistName: 'Christo and Jeanne-Claude', imageUrl: '', wiki: '' },
];
