GET https://api.printify.com/v1/uploads.json HTTP/1.1
content-type: application/json;charset=utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzN2Q0YmQzMDM1ZmUxMWU5YTgwM2FiN2VlYjNjY2M5NyIsImp0aSI6IjU4MTk1NzZlMGJjYmZjNGRjMWNhYzAwZmFiYTE3Njg2ZTRlNGZiMTMwY2MxMDk4MjA2NmFjODI3YjhjMzdkMDkzYmIxYWQ3NzRjYzAxODI2IiwiaWF0IjoxNjc3MTM1NjczLjM3NTYwNSwibmJmIjoxNjc3MTM1NjczLjM3NTYwOSwiZXhwIjoxNzA4NjcxNjczLjM2ODQ1Miwic3ViIjoiMTE3ODYxNjgiLCJzY29wZXMiOlsic2hvcHMubWFuYWdlIiwic2hvcHMucmVhZCIsImNhdGFsb2cucmVhZCIsIm9yZGVycy5yZWFkIiwib3JkZXJzLndyaXRlIiwicHJvZHVjdHMucmVhZCIsInByb2R1Y3RzLndyaXRlIiwid2ViaG9va3MucmVhZCIsIndlYmhvb2tzLndyaXRlIiwidXBsb2Fkcy5yZWFkIiwidXBsb2Fkcy53cml0ZSIsInByaW50X3Byb3ZpZGVycy5yZWFkIl19.Aq_k798L3fDSD1xPT6x-EHt6xNU77HxfWUnJezuAWVvwlI3WP0gsSNTqZK-Mj5tlrJRR-hDzJizIewySYUc

# ###

# GET https://api.printify.com/v1/uploads/images.json HTTP/1.1
# content-type: application/json;charset=utf-8
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzN2Q0YmQzMDM1ZmUxMWU5YTgwM2FiN2VlYjNjY2M5NyIsImp0aSI6ImMzMGI0MjA4NzYxZTM5YzgzNzMwZTJkNTJhMGRlNGI3MGNhNjEwOTA5MjQyYmUwMjc2OTYyZDZmODI5M2ZmY2U5ZTZhNWQzODc2MWZjYTZmIiwiaWF0IjoxNjc2Nzk0NzkwLjcyMDcxMSwibmJmIjoxNjc2Nzk0NzkwLjcyMDcxMywiZXhwIjoxNzA4MzMwNzkwLjcxNTkzOSwic3ViIjoiMTE3ODYxNjgiLCJzY29wZXMiOlsic2hvcHMubWFuYWdlIiwic2hvcHMucmVhZCIsImNhdGFsb2cucmVhZCIsIm9yZGVycy5yZWFkIiwib3JkZXJzLndyaXRlIiwicHJvZHVjdHMucmVhZCIsInByb2R1Y3RzLndyaXRlIiwid2ViaG9va3MucmVhZCIsIndlYmhvb2tzLndyaXRlIiwidXBsb2Fkcy5yZWFkIiwidXBsb2Fkcy53cml0ZSIsInByaW50X3Byb3ZpZGVycy5yZWFkIl19.ARI94d_8g3LTnra0FY2_aUf_zXanXwZ04YGX2UeuyiN0Sc_4EAJ10Jn2PijIYrdlwBTX3kMuNZxuD9a2K_8

# {
#     "file_name":"BOWLOSOUP",
#     "url":"https://qd-uploads-and-transfers-dev.s3.amazonaws.com/Dall-E/1cb3463c-d6cc-4cc3-b0cd-16fb50647719/1cb3463c-d6cc-4cc3-b0cd-16fb50647719-2.png?AWSAccessKeyId=AKIAUO46JKWBGMQEFWYW&Expires=1676801502&Signature=p3NP9jgSsk7PjDw7lFpUFZ%2B3FDs%3D"
# }

###

POST http://localhost:3000/api/stripe/webhook HTTP/1.1
content-type: application/json

{
    "some": "data"
}