name: 🪐 Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/.gitignore'
      - 'assets/'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
      - name: Set version
        run: echo "VERSION=0.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Test version (write)
        run: echo ${VERSION}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # - name: Install prettier
      #   run: npm i -g prettier

      # - name: Install prettier-plugin-tailwindcss
      #   run: npm i -g prettier-plugin-tailwindcss

      # - name: Prettify code
      #   uses: creyD/prettier_action@v4.2
      #   with:
      #     # This part is also where you can pass other options, for example:
      #     prettier_options: --check **/*.{ts,tsx,js,jsx,md}
      #     only_changed: False

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run CI build
        run: npm run cibuild


      - name: Zip studio-build
        run: zip -r studio-portal.${{ env.VERSION }}.zip ./studio_build

      - name: Zip terraform
        run: zip -r studio-portal-terraform.${{ env.VERSION }}.zip ./terraform

      - name: Push a package to Octopus Deploy 🐙
        uses: OctopusDeploy/push-package-action@v3
        env:
          OCTOPUS_URL: ${{ secrets.SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.API_KEY }}
          OCTOPUS_SPACE: 'Default'
        with:
          packages: |
            studio-portal.${{ env.VERSION }}.zip
            studio-portal-terraform.zip 